/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Place } from "./Place";
export * as factories from "./factories";
export { Place__factory } from "./factories/Place__factory";
